plants/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('plantswebsite.urls', namespace="plantswebsite") ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plantswebsite/urls.py
from django.urls import path, include
from plantswebsite import views
from .views import PlantsDescriptionView, register

app_name = "plantswebsite"

urlpatterns = [
	path('home/', views.IndexView.as_view(), name="home"),
    path('contact/', views.ContactProfileView.as_view(), name="contact"),
	path('subscribe/', views.subscriber, name="subscribe"),
    path('shop/', views.ShopView.as_view(), name="shop"),
	path('shop/<int:id>/', views.PlantsDescription, name="plantsdescription"),
	path('home/<int:id>/', views.PlantsDescription, name="plantsdescription"),
	path('plantsdescription/', PlantsDescriptionView.as_view(), name="pd"),
	path('plants-list', views.plantsSearchList),
	path('searchPlantsProducts', views.searchPlantsProducts, name="searchPlantsProducts"),
	# path('add-to-cart/<int:id>/', views.add_to_cart, name="add-to-cart"),
	path('register/', views.register, name="register"),
	path('login/', views.loginpage, name="login"),
	path('logout/', views.logoutpage, name="logout"),
	path('userpasswordreset', views.userpasswordreset, name="userpasswordreset"),

	path('add-to-cart', views.addtocart, name="addtocart"),
	path('cart/', views.viewcart, name="cart"),
	path('update-cart', views.updatecart, name="updatecart"),
	path('delete-cart-item', views.deletecartitem, name="deletecartitem"),

	path('checkout', views.checkout, name="checkout"),
	path('placeorder', views.placeorder, name="placeorder"),
	path('render_pdf_view/<str:t_no>', views.render_pdf_view, name="render_pdf_view"),

	path('proceed-to-pay', views.razorpaycheck),
	path('my-orders', views.orders, name="myorders"),
	path('viewuserorders/<str:t_no>', views.viewuserorders, name="viewuserorders"),
	]

plantswebsite/forms.py
from django import forms
from django.forms import fields
from .models import ContactProfile, User
from django.contrib.auth.forms import UserCreationForm

class ContactProfileForm(forms.ModelForm):
    name = forms.CharField(max_length=100,required=True)
    email = forms.EmailField(max_length=254,required=True)
    message = forms.CharField(max_length=1000,required=True)

    class Meta:
        model = ContactProfile
        fields = ('name','email','message',)

class CustomUserForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"class":"contact__input"}))
    email = forms.CharField(widget=forms.TextInput(attrs={"class":"contact__input"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"class":"contact__input"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"class":"contact__input"}))
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

plantswebsite/views.py
from time import timezone
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import *
from django.utils import timezone
from django.views import generic
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
import random
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa


# Create your views here.
class IndexView(generic.TemplateView):
    template_name = "plantswebsite/index.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        landingscreens = LandingScreen.objects.get()
        abouts = About.objects.get()
        plants = Plants.objects.all()
        plants_s = Plants.objects.all()[:6]
        plants_ss = Plants.objects.all()[:4]

        context["landingscreens"] = landingscreens
        context["abouts"] = abouts
        context["plants"] = plants
        context["plants_s"] = plants_s #check out our products section
        context["plants_ss"] = plants_ss #trending plants

        return context

class ContactProfileView(generic.FormView):
    template_name = "plantswebsite/contact.html"
    form_class = ContactProfileForm
    success_url = "/home/"

    def form_valid(self, form):
        form.save()
        messages.success(self.request, "Thank you. We will be in touch soon.")
        return super().form_valid(form)

class ShopView(generic.TemplateView):
    template_name = "plantswebsite/shop.html"
    # form_class = ContactProfileForm
    success_url = "/home/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        shop_plants = Plants.objects.all()

        context["shop_plants"] = shop_plants

        return context

def PlantsDescription(request, id):
    plants_object = Plants.objects.get(id=id)
    return render(request, 'plantswebsite/plants_description.html', {'plants_object':plants_object})

class PlantsDescriptionView(ListView):
    model = Plants
    template_name = "plants_description.html"

def register(request):
    form = CustomUserForm()
    if request.method == 'POST':
        form = CustomUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,"Registered Successfully! Login to continue")
            return redirect('/login')
    context = {'form':form}
    return render(request, "plantswebsite/register.html", context)

def loginpage(request):
    if request.user.is_authenticated:
        messages.warning(request,"Logged in Already!")
        return redirect("/home")
    else:
        if request.method == 'POST':
            name = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=name, password=password)
            if user is not None:
                login(request, user)
                messages.success(request,"Logged in Successfully!")
                return redirect('/home')
            else:
                messages.error(request,"Invalid Username or Password!")
                return redirect('/login')
        return render(request, 'plantswebsite/login.html')

def logoutpage(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect("/home")

def addtocart(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            product_id = int(request.POST.get('product_id'))
            product_check = Plants.objects.get(id=product_id)
            if(product_check):
                if(Cart.objects.filter(user=request.user.id, product_id=product_id)):
                    return JsonResponse({'status':'Product already in cart'})
                else:
                    product_quantity = int(request.POST.get('product_quantity'))

                    if product_check.quantity >= product_quantity:
                        Cart.objects.create(user=request.user, product_id=product_id, product_quantity=product_quantity)
                        return JsonResponse({'status':'Product addded to cart'})
                    else:
                        return JsonResponse({'status':'Only' + str(product_check.quantity) + "quantity is available"})
            else:
                return JsonResponse({'status':'No product found'})
        else:
            return JsonResponse({'status':'Login to Continue'})
    return redirect("/home")

def viewcart(request):
    cart = Cart.objects.filter(user=request.user)
    context = {'cart':cart}
    return render(request,"plantswebsite/cart.html", context)

def updatecart(request):
    if request.method == "POST":
        product_id = int(request.POST.get('product_id'))
        if (Cart.objects.filter(user=request.user, product_id=product_id)):
            product_quantity = int(request.POST.get('product_quantity'))
            cart = Cart.objects.get(product_id=product_id, user=request.user)
            cart.product_quantity = product_quantity
            cart.save()
            return JsonResponse({'status':"Cart Updated Successfully!",'product_quantity':cart.product_quantity})
    return redirect("/home")


def deletecartitem(request):
    if request.method == "POST":
        product_id = int(request.POST.get('product_id'))
        if (Cart.objects.filter(user=request.user, product_id=product_id)):
            cartitem = Cart.objects.get(product_id=product_id, user=request.user)
            cartitem.delete()
        return JsonResponse({'status':"Deleted Successfully!"})
    return redirect("/home")

@login_required(login_url='login')
def checkout(request):
    rawCartItems = Cart.objects.filter(user=request.user)
    for item in rawCartItems:
        if item.product_quantity > item.product.quantity:
            Cart.objects.delete(id=item.id)

    cartItems = Cart.objects.filter(user=request.user)
    total_price = 0
    for item in cartItems:
        total_price = total_price + item.product.price * item.product_quantity

    userProfile = Profile.objects.filter(user=request.user).first()

    context = {'cartItems': cartItems, 'totalPrice':total_price, 'userProfile':userProfile}
    return render(request, "plantswebsite/checkout.html", context)

@login_required(login_url='login')
def placeorder(request):
    if request.method == 'POST':

        currentUser = User.objects.filter(id=request.user.id).first()

        if not currentUser.first_name:
            currentUser.first_name = request.POST.get('firstname')
            currentUser.last_name = request.POST.get('lastname')
            currentUser.save()

        if not Profile.objects.filter(user=request.user):
            userProfile = Profile()
            userProfile.user = request.user
            userProfile.phone = request.POST.get('phone')
            userProfile.address = request.POST.get('address')
            userProfile.city = request.POST.get('city')
            userProfile.state = request.POST.get('state')
            userProfile.country = request.POST.get('country')
            userProfile.pincode = request.POST.get('pincode')
            userProfile.save()

        newOrder = Order()
        newOrder.user = request.user
        newOrder.fname = request.POST.get('firstname')
        newOrder.lname = request.POST.get('lastname')
        newOrder.email = request.POST.get('email')
        newOrder.phone = request.POST.get('phone')
        newOrder.address = request.POST.get('address')
        newOrder.city = request.POST.get('city')
        newOrder.state = request.POST.get('state')
        newOrder.country = request.POST.get('country')
        newOrder.pincode = request.POST.get('pincode')

        newOrder.payment_mode = request.POST.get('payment_mode')
        newOrder.payment_id = request.POST.get('payment_id')

        cart = Cart.objects.filter(user=request.user)
        cart_total_price = 0
        for item in cart:
            cart_total_price = cart_total_price + item.product.price * item.product_quantity

        newOrder.total_price = cart_total_price

        trackNumber = newOrder.fname[:5] + str(random.randint(1111111,9999999))
        while Order.objects.filter(tracking_number = trackNumber) is None:
            trackNumber = newOrder.fname[:5] + str(random.randint(1111111,9999999))

        newOrder.tracking_number = trackNumber
        #Update the order status
        newOrder.status = 'COMPLETED' 
        newOrder.save()

        newOrderItems = Cart.objects.filter(user=request.user)
        #To create in OrderItem model
        for items in newOrderItems:
            OrderItem.objects.create(
                order = newOrder,
                product = items.product,
                price = items.product.price,
                quantity = items.product_quantity
            )
            # To decrease from available Plants stock
            orderplants = Plants.objects.filter(id=items.product_id).first()
            orderplants.quantity = orderplants.quantity - items.product_quantity
            orderplants.save()

        # To clear users cart
        Cart.objects.filter(user=request.user).delete()
        
        # return JsonResponse({'status':"Order Placed Successfully!"})

        payMode = request.POST.get('payment_mode')
        if (payMode == "Paid with Razorpay"):
            return JsonResponse({'status':"Order Placed Successfully!"})
        else:
            messages.success(request, "Order Placed Successfully!")

    return redirect('/home')

@login_required(login_url='login')
def razorpaycheck(request):
    cart = Cart.objects.filter(user=request.user)
    total_price = 0
    for item in cart:

plantswebsite/templates/plantswebsite/partials/footer.html
{% load static %}
<!--==========FOOTER===========-->
<footer class="footer section">
    <div class="footer__container container grid">
        <div class="footer__content">
            <a href="#" class="footer__logo">
                <i class="ri-leaf-line footer__logo-icon"></i> Recent Gardener
            </a>

            <h3 class="footer__title">
                Subscribe to our newsletter <br> to stay connected 
            </h3>
            <form id="subscribeForm" method="POST" action="/subscribe/">
                {% csrf_token %}
                <div class="footer__subscribe">  
                    <input type="email" name="SubcribeEmail" placeholder="Enter mail" class="footer__input" required>
                    <button class="button button--flex footer__button">
                        Subscribe
                        <i class="ri-notification-2-line button__icon"></i>
                    </button>
                </div>
            </form>
        </div>

        <div class="footer_content">
            <h3 class="footer__title">Our Address</h3>

            <ul class="footer__data">
                <li class="footer__information">123456 - India</li>
                <li class="footer__information">Bangalore - Karnataka</li>
                <li class="footer__information">123-456-789</li>
            </ul>
        </div>
        <div class="footer_content">
            <h3 class="footer__title">Contact US</h3>

            <ul class="footer__data">
                <li class="footer__information"><a href="{% url 'plantswebsite:contact' %}" class="button--link button--flex"> Share your thoughts! </a></li>
                <li class="footer__information"><a href="{% url 'plantswebsite:contact' %}" class="button--link button--flex"> Terms and Conditions </a></li>
                <li class="footer__information"><a href="{% url 'plantswebsite:contact' %}" class="button--link button--flex"> Privacy Policy </a></li>
                <li class="footer__information">+91- 123456</li>
                <div class="footer__social">
                    <a href="https://www.facebook.com" class="footer__social-link">
                        <i class="ri-facebook-fill"></i>
                    </a>
                    <a href="https://www.instagram.com" class="footer__social-link">
                        <i class="ri-instagram-fill"></i>
                    </a>
                    <a href="https://www.twitter.com" class="footer__social-link">
                        <i class="ri-twitter-fill"></i>
                    </a>
                </div>
            </ul>
        </div>
        <div class="footer_content">
            <h3 class="footer__title">We accept all credit cards</h3>

            <div class="footer_cards">
                <img src="{% static 'images/card1.png' %}" alt="" class="footer__card">
                <img src="{% static 'images/card2.png' %}" alt="" class="footer__card">
                <img src="{% static 'images/card3.png' %}" alt="" class="footer__card">
                <img src="{% static 'images/card4.png' %}" alt="" class="footer__card">
            </div>
        </div>
    </div>

    <p class="footer__copy">&#169; RecentGardener. All Rights Reserved.</p>
</footer>

plantswebsite/templates/plantswebsite/partials/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
    {% endfor %}
{% endif %}

plantswebsite/templates/plantswebsite/partials/nav.html
{% load static %}
<!-- ================================
Start Navigation Bar
================================= -->
<header class="header" id="header">
    <nav class="nav container">
        <a href="{% url 'plantswebsite:home' %}" class="nav__logo">
            <i class="ri-leaf-line nav__logo-icon"></i> Recent Gardener
        </a>

        <div class="nav__menu" id="nav-menu">
            <ul class="nav__list">
                <li class="nav__item">
                    {% comment %} <a href="{% url 'plantswebsite:home' %}" class="nav__link active-link">Home</a> {% endcomment %}
                    <a href="{% url 'plantswebsite:home' %}" class="nav__link">Home</a>
                </li>
                <li class="nav__item">
                    <a href="{% url 'plantswebsite:shop' %}" class="nav__link">Shop</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav__item">
                        <a href="{% url 'plantswebsite:cart' %}" class="nav__link qty-input">Cart{{ cart.product_quantity }}</a>
                    </li>
                {% else %}
                    <li class="nav__item">
                        <a href="{% url 'plantswebsite:login' %}" class="nav__link">Cart</a>
                    </li>
                {% endif %}
                {% if request.user.is_authenticated %}
                    <li class="nav__item">
                        <a href="{% url 'plantswebsite:myorders' %}" class="nav__link">My Orders</a>
                    </li>
                {% endif %}
                {% if request.user.is_authenticated %}
                <li class="nav__item">
                    <a href="{% url 'plantswebsite:logout' %}" class="nav__link">Logout</a>
                </li>
            {% else %}
                <li class="nav__item">
                    <a href="{% url 'plantswebsite:login' %}" class="nav__link">Login/Register</a>
                </li>
            {% endif %}
                <li class="nav__item">
                    <a href="{% url 'plantswebsite:contact' %}" class="nav__link">Contact Us</a>
                </li>
            </ul>

            <div class="nav__close" id="nav-close">
                <i class="ri-close-line"></i>
            </div>
        </div>

        <div class="nav__btns">
            <!-- Theme Change Button -->
            <i class="ri-moon-line change-theme" id="theme-button"></i>

            <div class="nav__toggle" id="nav-toggle">
                <i class="ri-menu-line"></i>
            </div>
        </div>
    </nav>
    
</header>

<!-- ================================
End Navigation Bar
================================= -->