plants/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('plantswebsite.urls', namespace="plantswebsite") ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plantswebsite/urls.py
from django.urls import path, include
from plantswebsite import views
from .views import PlantsDescriptionView, register

app_name = "plantswebsite"

urlpatterns = [
	path('home/', views.IndexView.as_view(), name="home"),
    path('contact/', views.ContactProfileView.as_view(), name="contact"),
	path('subscribe/', views.subscriber, name="subscribe"),
    path('shop/', views.ShopView.as_view(), name="shop"),
	path('shop/<int:id>/', views.PlantsDescription, name="plantsdescription"),
	path('home/<int:id>/', views.PlantsDescription, name="plantsdescription"),
	path('plantsdescription/', PlantsDescriptionView.as_view(), name="pd"),
	path('plants-list', views.plantsSearchList),
	path('searchPlantsProducts', views.searchPlantsProducts, name="searchPlantsProducts"),
	# path('add-to-cart/<int:id>/', views.add_to_cart, name="add-to-cart"),
	path('register/', views.register, name="register"),
	path('login/', views.loginpage, name="login"),
	path('logout/', views.logoutpage, name="logout"),
	path('userpasswordreset', views.userpasswordreset, name="userpasswordreset"),

	path('add-to-cart', views.addtocart, name="addtocart"),
	path('cart/', views.viewcart, name="cart"),
	path('update-cart', views.updatecart, name="updatecart"),
	path('delete-cart-item', views.deletecartitem, name="deletecartitem"),

	path('checkout', views.checkout, name="checkout"),
	path('placeorder', views.placeorder, name="placeorder"),
	path('render_pdf_view/<str:t_no>', views.render_pdf_view, name="render_pdf_view"),

	path('proceed-to-pay', views.razorpaycheck),
	path('my-orders', views.orders, name="myorders"),
	path('viewuserorders/<str:t_no>', views.viewuserorders, name="viewuserorders"),
	]

plantswebsite/forms.py
from django import forms
from django.forms import fields
from .models import ContactProfile, User
from django.contrib.auth.forms import UserCreationForm

class ContactProfileForm(forms.ModelForm):
    name = forms.CharField(max_length=100,required=True)
    email = forms.EmailField(max_length=254,required=True)
    message = forms.CharField(max_length=1000,required=True)

    class Meta:
        model = ContactProfile
        fields = ('name','email','message',)

class CustomUserForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"class":"contact__input"}))
    email = forms.CharField(widget=forms.TextInput(attrs={"class":"contact__input"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"class":"contact__input"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"class":"contact__input"}))
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

plantswebsite/views.py
from time import timezone
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import *
from django.utils import timezone
from django.views import generic
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
import random
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa


# Create your views here.
class IndexView(generic.TemplateView):
    template_name = "plantswebsite/index.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        landingscreens = LandingScreen.objects.get()
        abouts = About.objects.get()
        plants = Plants.objects.all()
        plants_s = Plants.objects.all()[:6]
        plants_ss = Plants.objects.all()[:4]

        context["landingscreens"] = landingscreens
        context["abouts"] = abouts
        context["plants"] = plants
        context["plants_s"] = plants_s #check out our products section
        context["plants_ss"] = plants_ss #trending plants

        return context

class ContactProfileView(generic.FormView):
    template_name = "plantswebsite/contact.html"
    form_class = ContactProfileForm
    success_url = "/home/"

    def form_valid(self, form):
        form.save()
        messages.success(self.request, "Thank you. We will be in touch soon.")
        return super().form_valid(form)

class ShopView(generic.TemplateView):
    template_name = "plantswebsite/shop.html"
    # form_class = ContactProfileForm
    success_url = "/home/"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        shop_plants = Plants.objects.all()

        context["shop_plants"] = shop_plants

        return context

def PlantsDescription(request, id):
    plants_object = Plants.objects.get(id=id)
    return render(request, 'plantswebsite/plants_description.html', {'plants_object':plants_object})

class PlantsDescriptionView(ListView):
    model = Plants
    template_name = "plants_description.html"

def register(request):
    form = CustomUserForm()
    if request.method == 'POST':
        form = CustomUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,"Registered Successfully! Login to continue")
            return redirect('/login')
    context = {'form':form}
    return render(request, "plantswebsite/register.html", context)

def loginpage(request):
    if request.user.is_authenticated:
        messages.warning(request,"Logged in Already!")
        return redirect("/home")
    else:
        if request.method == 'POST':
            name = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=name, password=password)
            if user is not None:
                login(request, user)
                messages.success(request,"Logged in Successfully!")
                return redirect('/home')
            else:
                messages.error(request,"Invalid Username or Password!")
                return redirect('/login')
        return render(request, 'plantswebsite/login.html')

def logoutpage(request):
    if request.user.is_authenticated:
        logout(request)
    return redirect("/home")

def addtocart(request):
    if request.method == 'POST':
        if request.user.is_authenticated:
            product_id = int(request.POST.get('product_id'))
            product_check = Plants.objects.get(id=product_id)
            if(product_check):
                if(Cart.objects.filter(user=request.user.id, product_id=product_id)):
                    return JsonResponse({'status':'Product already in cart'})
                else:
                    product_quantity = int(request.POST.get('product_quantity'))

                    if product_check.quantity >= product_quantity:
                        Cart.objects.create(user=request.user, product_id=product_id, product_quantity=product_quantity)
                        return JsonResponse({'status':'Product addded to cart'})
                    else:
                        return JsonResponse({'status':'Only' + str(product_check.quantity) + "quantity is available"})
            else:
                return JsonResponse({'status':'No product found'})
        else:
            return JsonResponse({'status':'Login to Continue'})
    return redirect("/home")

def viewcart(request):
    cart = Cart.objects.filter(user=request.user)
    context = {'cart':cart}
    return render(request,"plantswebsite/cart.html", context)

def updatecart(request):
    if request.method == "POST":
        product_id = int(request.POST.get('product_id'))
        if (Cart.objects.filter(user=request.user, product_id=product_id)):
            product_quantity = int(request.POST.get('product_quantity'))
            cart = Cart.objects.get(product_id=product_id, user=request.user)
            cart.product_quantity = product_quantity
            cart.save()
            return JsonResponse({'status':"Cart Updated Successfully!",'product_quantity':cart.product_quantity})
    return redirect("/home")


def deletecartitem(request):
    if request.method == "POST":
        product_id = int(request.POST.get('product_id'))
        if (Cart.objects.filter(user=request.user, product_id=product_id)):
            cartitem = Cart.objects.get(product_id=product_id, user=request.user)
            cartitem.delete()
        return JsonResponse({'status':"Deleted Successfully!"})
    return redirect("/home")

@login_required(login_url='login')
def checkout(request):
    rawCartItems = Cart.objects.filter(user=request.user)
    for item in rawCartItems:
        if item.product_quantity > item.product.quantity:
            Cart.objects.delete(id=item.id)

    cartItems = Cart.objects.filter(user=request.user)
    total_price = 0
    for item in cartItems:
        total_price = total_price + item.product.price * item.product_quantity

    userProfile = Profile.objects.filter(user=request.user).first()

    context = {'cartItems': cartItems, 'totalPrice':total_price, 'userProfile':userProfile}
    return render(request, "plantswebsite/checkout.html", context)

@login_required(login_url='login')
def placeorder(request):
    if request.method == 'POST':

        currentUser = User.objects.filter(id=request.user.id).first()

        if not currentUser.first_name:
            currentUser.first_name = request.POST.get('firstname')
            currentUser.last_name = request.POST.get('lastname')
            currentUser.save()

        if not Profile.objects.filter(user=request.user):
            userProfile = Profile()
            userProfile.user = request.user
            userProfile.phone = request.POST.get('phone')
            userProfile.address = request.POST.get('address')
            userProfile.city = request.POST.get('city')
            userProfile.state = request.POST.get('state')
            userProfile.country = request.POST.get('country')
            userProfile.pincode = request.POST.get('pincode')
            userProfile.save()

        newOrder = Order()
        newOrder.user = request.user
        newOrder.fname = request.POST.get('firstname')
        newOrder.lname = request.POST.get('lastname')
        newOrder.email = request.POST.get('email')
        newOrder.phone = request.POST.get('phone')
        newOrder.address = request.POST.get('address')
        newOrder.city = request.POST.get('city')
        newOrder.state = request.POST.get('state')
        newOrder.country = request.POST.get('country')
        newOrder.pincode = request.POST.get('pincode')

        newOrder.payment_mode = request.POST.get('payment_mode')
        newOrder.payment_id = request.POST.get('payment_id')

        cart = Cart.objects.filter(user=request.user)
        cart_total_price = 0
        for item in cart:
            cart_total_price = cart_total_price + item.product.price * item.product_quantity

        newOrder.total_price = cart_total_price

        trackNumber = newOrder.fname[:5] + str(random.randint(1111111,9999999))
        while Order.objects.filter(tracking_number = trackNumber) is None:
            trackNumber = newOrder.fname[:5] + str(random.randint(1111111,9999999))

        newOrder.tracking_number = trackNumber
        #Update the order status
        newOrder.status = 'COMPLETED' 
        newOrder.save()

        newOrderItems = Cart.objects.filter(user=request.user)
        #To create in OrderItem model
        for items in newOrderItems:
            OrderItem.objects.create(
                order = newOrder,
                product = items.product,
                price = items.product.price,
                quantity = items.product_quantity
            )
            # To decrease from available Plants stock
            orderplants = Plants.objects.filter(id=items.product_id).first()
            orderplants.quantity = orderplants.quantity - items.product_quantity
            orderplants.save()

        # To clear users cart
        Cart.objects.filter(user=request.user).delete()
        
        # return JsonResponse({'status':"Order Placed Successfully!"})

        payMode = request.POST.get('payment_mode')
        if (payMode == "Paid with Razorpay"):
            return JsonResponse({'status':"Order Placed Successfully!"})
        else:
            messages.success(request, "Order Placed Successfully!")

    return redirect('/home')

@login_required(login_url='login')
def razorpaycheck(request):
    cart = Cart.objects.filter(user=request.user)
    total_price = 0
    for item in cart:

plantswebsite/templates/plantswebsite/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Pradeep | Plants{% endblock %}</title>
    <meta name="author" content="Pradeep | Plants">
    <link rel="canonical" href="{{request.path}}"/>
    <link rel="home" href="{% url 'plantswebsite:home' %}"/>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="keywords" content="{% block keywords %}{% endblock %}">
    <!--FAVICON-->
    <link rel="shortcut icon" href="static/images/favicon.png" type="image/x-icon">
    <!--REMIX ICONS-->
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
    

    <!-- ================================
    Start CSS
    ================================= -->
    {% comment %} <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> {% endcomment %}
    <link rel="stylesheet" href="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% block extend_header%}{%endblock%}
    <!-- ================================
    End CSS
    ================================= -->

</head>
<body>
    {% comment %} {% block content %}
    <p>Hello DJ application</p>
    {% endblock %} {% endcomment %}
    {% include 'plantswebsite/partials/messages.html' %}
    {% include 'plantswebsite/partials/nav.html' %}

    {% block content %}
    {% endblock %}

    {% include 'plantswebsite/partials/footer.html' %}

    <!-- ================================
    Start Scripts
    ================================= -->
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"> </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    {% comment %} <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script> {% endcomment %}
    <script src="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    <script>
        var availableTags = [];
        $.ajax({
            method: "GET",
            url: "/plants-list",
            success: function (response){
                startAutoComplete(response);
            }
        });
        function startAutoComplete(availableTags){
            $( "#searchPlants" ).autocomplete({
                source: availableTags
                });
        }
    </script>
    {% comment %} <script src="{% static 'js/script.js' %}"></script> {% endcomment %}

    <!--SCROLL UP-->
    <a href="#" class="scrollup" id="scroll-up">
        <i class="ri-arrow-up-fill scrollup__icon"></i>
    </a>
    <!--SCROLL REVEAL-->
    <script src="{%static 'js/scrollreveal.min.js' %}"> 
// this file is downloaded from scrollrevealjs.org. github>js>--->raw format
// <!--OR you can include the script btw the script tags, src="https://unpkg.com/scrollreveal">
    </script>

    <!--main.js-->
    <script src="{% static 'js/script.js' %}">

    </script>
    <script src="{% static 'js/custom.js' %}"></script>
    {% block extend_footer %}{%endblock%}
    {% comment %} Razorpay Checkout {% endcomment %}
    <script src="{% static 'js/checkout.js' %}"></script>
    <!-- ================================
    End Scripts
    ================================= -->
</body>
</html>

plantswebsite/templates/plantswebsite/cart.html
{% extends 'plantswebsite/base.html' %}
{% load static %}


{% block title %}Recent Gardener | Cart{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}


{% block content %}
<!--==========CART PAGE===========-->
<section class="cartdata section container" id="viewcart">
        {% if cart %}
            {% for item in cart %}
            <div class="footer__container container grid product_data">
                <div class="footer_content">
                    <img src="{{ item.product.image.url }}" height="70px" width="60px" alt="Product Image">
                </div>

                <div class="footer_content">
                    <ul class="footer__data">
                        <li class="footer__information">{{ item.product.name }}</li>
                        <li class="footer__information">₹ {{ item.product.price }}</li>
                    </ul>
                </div>
                <div class="footer_content">
                    <input type="hidden" class="prod_id" value="{{ item.product_id }}">
                    {% csrf_token %}
                    {% if item.product.quantity >= item.product_quantity %}
                    <ul class="footer__data">
                        <li class="footer__information">
                            <button class="button button--flex incdec__button decrement-btn changeQuantity ">-</button>
                            <input type="text" name="quantity" class="incdec__input form-control qty-input text-center" value="{{ item.product_quantity }}">
                            <button class="button button--flex incdec__button increment-btn changeQuantity">+</button>
                        </li>
                    </ul>
                    {% else %}
                        <h6>Out of Stock</h6>
                    {% endif %}
                </div>
                <div class="footer_content">
                    <div class="footer_cards">
                        <a href="#" class="button button--flex delete-cart-item">
                            Remove <i class="ri-delete-bin-line button__icon"></i>
                        </a>
                    </div>
                </div>
            </div>
        </br>
            {% endfor %}
            <div class="footer_content">
                <div class="footer_cards">
                    <a href="{% url 'plantswebsite:checkout' %}" class="button button--flex">
                        Checkout <i class="ri-arrow-right-up-line button__icon"></i>
                    </a>
                </div>
            </div>
        {% else %}
            <h4 class="section__title-center">Your Cart is Empty!</h4>
            </br>
            <h5 class="section__title-center">Get Started! <a href="{% url 'plantswebsite:shop' %}" class="footer__logo-icon"> Shop Now.</a></h5>
        {% endif %}

</section>
{%endblock%}

plantswebsite/templates/plantswebsite/checkout.html
{% extends 'plantswebsite/base.html' %}
{% load static %}


{% block title %}Recent Gardener | Checkout{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}


{% block content %}
<!--==========CHECKOUT PAGE===========-->
<section class="checkout section" id="checkout">
    <div class="contact__container container grid">
{% comment %} First Half {% endcomment %}
        <form id="checkoutForm" method="POST" action="{% url 'plantswebsite:placeorder' %}" class="checkout__form">
            {% csrf_token %}
            <div class="checkout__inputs contact__container">
                <div class="checkout__content">
                    <input type="text" value="{{ request.user.first_name }}" name="firstname" placeholder=" " class="checkout__input" required>
                    <label for="" class="checkout__label">First Name</label>
                    
                </div>
                <div class="checkout__content">
                    <input type="text" value="{{ request.user.last_name }}" name="lastname" placeholder=" " class="checkout__input" required>
                    <label for="" class="checkout__label">Last Name</label>
                    
                </div>
                <div class="checkout__content">
                    <input type="email" value="{{ request.user.email }}" name="email" placeholder=" " class="checkout__input" required>
                    <label for="" class="checkout__label">Email</label>
                    
                </div>
                <div class="checkout__content">
                    <input type="number" value="{{ userProfile.phone }}" name="phone" placeholder=" " class="checkout__input" required>
                    <label for="" class="checkout__label">Phone</label>
                    
                </div>
                <div class="checkout__content">
                    <input type="address" value="{{ userProfile.address }}" name="address" placeholder=" " class="checkout__input" required>
                    <label for="" class="checkout__label">Address</label>
                    
                </div>
                <div class="checkout__content">
                    <input type="text" value="{{ userProfile.city }}" name="city" placeholder=" " class="checkout__input" required>
                    <label for="" class="checkout__label">City</label>
                    
                </div>
                <div class="checkout__content">
                    <input type="text" value="{{ userProfile.state }}" name="state" placeholder=" " class="checkout__input" required>
                    <label for="" class="checkout__label">State</label>
                    
                </div>
                <div class="checkout__content">
                    <input type="text" value="{{ userProfile.country }}" name="country" placeholder=" " class="checkout__input" required>
                    <label for="" class="checkout__label">Country</label>
                    
                </div>
                <div class="checkout__content">
                    <input type="number" value="{{ userProfile.pincode }}" name="pincode" placeholder=" " class="checkout__input" required>
                    <label for="" class="checkout__label">Pin Code</label>
                    
                </div>
            </div>
            <div class="contact__container">
                <input type="hidden" value="COD" name="payment_mode">
                <button type="submit" class="button button--flex">
                    Place Order | COD
                    <i class="ri-arrow-right-up-line button__icon"></i>
                </button>
                <button type="button" class="button button--flex payWithRazorpay">
                    Pay with Razorpay
                    <i class="ri-arrow-right-up-line button__icon"></i>
                </button>
            </div>
        </form>
{% comment %} Second half {% endcomment %}
        <div class="contact__box checkout_table">
            <h2 class="section__title-centers">
                Order Summary
            </h2>
            <div class="checkout__data section__title-table">
                <div class="contact__information">
                    {% if cartItems %}
                        <table class="table-stripeds">
                            <thead>
                                <tr>
                                    <th class="table_th">Product</th>
                                    <th class="table_th">Quantity</th>
                                    <th class="table_th">Price</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for item in cartItems %}
                                    <tr>
                                        <td class="table_td">
                                            <img src="{{ item.product.image.url }}" class="me-2" height="30px" width="30px">
                                            {{ item.product.name }}
                                        </td>
                                        <td class="table_td">{{ item.product_quantity }}</td>
                                        <td class="table_td">{{ item.product.price }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        
                        <div class="footer_content">
                            <div class="footer_cards">
                                <h4 class="section__title-centers">
                                    Grand Total:
                                    <span> ₹ {{ totalPrice }} </span>
                                </h4>
                                <a href="#" class="button button--flex section__title-centers">
                                    Place Order
                                </a>
                            </div>
                        </div>
                    {% else %}
                        <h4 class="section__title-center">Your Checkout is Empty!</h4>
                        </br>
                        <h5 class="section__title-center">Get Started! <a href="{% url 'plantswebsite:shop' %}" class="footer__logo-icon"> Shop Now.</a></h5>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
</section>

{%endblock%}

{% block scripts %}
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
{% endblock scripts %}

plantswebsite/templates/plantswebsite/login.html
{% extends 'plantswebsite/base.html' %}
{% load static %} 


{% block title %}Recent Gardener | Login{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %} 


{% block content %}

{% comment %} {{form.as_p}} {% endcomment %}
<section class="contact section container" id="login">
<div class="contact__container grid">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="">
                <div class="card mt-3 shadow contact__inputs">
                    <div class="card-body ">
                        <form action="" method="POST" class="contact__form">
                            {% csrf_token %}
                            <div class="contact__inputs">
                                <div class="text-center">
                                    <h2> Login to Recent Gardener </h2>
                                </div>
                                {% comment %} <hr> {% endcomment %}
                                <div class="contact__content">
                                    <input type="text" name="username" placeholder=" " class="contact__input">
                                    <label for="" class="contact__label"> Username </label>
                                </div>
                                <div class="form-group contact__content">
                                    <input type="Password" name="password" placeholder=" " class="contact__input">
                                    <label for="" class="contact__label"> Password </label>
                                </div>

                                <button type='submit' class="button button--flex">
                                    Login
                                    <i class="ri-login-circle-line button__icon"></i>
                                </button> 
                            </div>
                        </form>
                        <a href="{% url 'plantswebsite:userpasswordreset' %} " class="footer__social-link"> Forgot Password?</a>
                        <h6>Create an account?<a href="{% url 'plantswebsite:register' %} " class="footer__social-link"> Register</a></h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</section>
{%endblock%}

plantswebsite/templates/plantswebsite/userorders.html
{% extends 'plantswebsite/base.html' %}
{% load static %}


{% block title %}Recent Gardener | My Orders{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}


{% block content %}
<!--==========My Orders PAGE===========-->
<section class="myordersdata section container" id="viewmyorders">
    {% if userOrders %}
        {% for order in userOrders %}
        <div class="footer__container container grid product_data">
            <div class="footer_content">
                {% comment %} <img src="{{ order.product.image.url }}" height="70px" width="60px" alt="Product Image"> {% endcomment %}
                <h3>{{ order.tracking_number }}</h3>
            </div>

            <div class="footer_content">
                <ul class="footer__data">
                    <li class="footer__information">₹ {{ order.total_price }}</li>
                    <li class="footer__information"><h5>{{ order.created_at }}</h5></li>
                </ul>
            </div>
            <div class="footer_content">
                <ul class="footer__data">
                    <li class="footer__information">
                        {{ order.status }}
                    </li>
                </ul>
            </div>
            <div class="footer_content">
                <div class="footer_cards">
                    <a href="{% url 'plantswebsite:viewuserorders' order.tracking_number %}" class="button button--flex">
                        View <i class="ri-arrow-right-up-line button__icon"></i>
                    </a>
                </div>
            </div>
        </div>
        </br>
        {% endfor %}
    {% else %}
        <h4 class="section__title-center">My Orders is Empty!</h4>
        </br>
        <h5 class="section__title-center">Get Started! <a href="{% url 'plantswebsite:shop' %}" class="footer__logo-icon"> Shop Now.</a></h5>
    {% endif %}

</section>


{%endblock%}